name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Flutter Runner
  # You may pin to the exact commit or the version.
  # uses: jddeep/Flutter-Runner@56254d611d8b799e297ab6f81ab4ec5dd0d128a2
      uses: jddeep/Flutter-Runner@1.2.0
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run tests
      run: flutter test
    - name: Build APK
      run: flutter build apk --release
      
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        script: "your-deployment-script.sh"
